### ISSUE TITLE
심혈관 이벤트 시퀸스 마이닝을 위한 이벤트 테이블 갱신

### ISSUE THREAD

**Issue by yuna12** [linewalks/catalog#13]
**개요 및 요청사항**
정확한 시퀸스 마이닝을 위해 이벤트 테이블, 또는 이벤트의 타임스탬프를 정정합니다.

적용 사항
- [x] event의 그룹화
- [x] timestamp 보정
- [x] timestamp 의 date_trunc(Truncate to specified precision)

**결과물**
- 갱신된 analysis.cardio_events

**완료 기준**
- [x] @hurcy confirmation

**관련 이슈**
ref #12 #17

**Comment by hurcy** [comment]
@yuna12 적용사항이 모두 반영되었으므로, 이슈를 닫아도 되겠습니다.
