### ISSUE TITLE
Sankey 용 예제 생성

### ISSUE THREAD

**Issue by hurcy** [linewalks/catalog#16]
export 포맷 예시(output/sankey_mace.json)를 참조하여 
모든 이벤트 카탈로그에 적용하고 output/ 디렉토리 아래 예시 파일을 추가합니다.

- 브랜치: export_for_sankey
- 파일명: sankey_*.json (예: sankey_diagnosis.json)

- [x] 질병 이벤트
- [x] 입원 이벤트
- [x] 투약 이벤트
- [x] 검사 이벤트

**Comment by paulsoh** [comment]
1. 데이터 형태는 [이 형태](https://github.com/linewalks/clinical-charts/blob/master/stories/mockdata/dataForSankey.js)와 동일하죠?
2. 위 케이스에 대한 story case도 추가해야될 필요가 있을까요?

**Comment by yuna12** [comment]
1. 네! 동일합니다  [진단명 이벤트](https://github.com/linewalks/catalog/blob/export_for_sankey/output/sankey_disease.json)에 대한 json 파일 입니다.

**Comment by hurcy** [comment]
@paulsoh 2. 네.
