### ISSUE TITLE
d_events에 admit에 대한 쿼리가 중복 실행

### ISSUE THREAD

**Issue by yuna12** [linewalks/catalog#18]
* 현상 : admit 카테고리에 대한 딕셔너리 정보가 중복되어 입력됨.

**Comment by yuna12** [comment]
* 원인 : 파이썬 테스트 코드에서 sql 문이 실행되지 않음.

**Comment by hurcy** [comment]
버그가 재현이 안됩니다.
이 문제가 재발시 이슈를 다시 열겠습니다.
