### ISSUE TITLE
SankeyComponent를 위한 MIMIC-3 데이터 내 Cardio Event 추출

### ISSUE THREAD

**Issue by paulsoh** [linewalks/catalog#26]
**개요 및 요청사항**
데이터를 정제하여 다음과 같은 tsv 파일을 출력합니다
```
pid\t seq\t start_date\t end_date\t duration\n
423\t"emergency,micu,..."\t"2014-01-31"\t ..\n
123\t"emergency,micu,..."\t"2014-01-31"\t ..\n
345\t"emergency,micu,..."\t"2014-01-31"\t ..\n 
...
```
**결과물**
- mimic_cardio_events_seq.tsv 파일

**완료 기준**
- [x] @paulsoh 확인

**Comment by hurcy** [comment]
@paulsoh  첨부파일 확인부탁드립니다.
1. mimic_cardio_events.tsv :  이벤트 딕셔너리
2. mimic_cardio_events_seq(id).tsv : 이벤트 ID 시퀸스
3. mimic_cardio_events_seq(name).tsv: 이벤트 이름 시퀸스

3이 이전에 드렸던 포맷과 동일한 것이고요. 혹시 필요할지 몰라서 ID로 치환한 버전(1,2)도 함께 드립니다.

[mimic_cardio_events.zip](https://github.com/linewalks/catalog/files/3150624/mimic_cardio_events.zip)
