### ISSUE TITLE
d_events 와 cardio_events 수정

### ISSUE THREAD

**Issue by yuna12** [linewalks/catalog#49]
**개요 및 요청사항**
procedure, lab, admit 등 6개 카테고리는 **전체 아이템**, diagnosis만 심혈관 질환 아이템만으로 입력합니다.
순서는 변하지 않는 6개의 카테고리 먼저 합니다.
업데이트 된 event_id에 맞게 cardio_event 테이블 수정합니다.

**결과물**
- d_events 테이블
- cardio_events 테이블

**완료 기준**
- [ ] @hurcy confirmation

**Comment by hurcy** [comment]
gitbot test
